# NUMPY ARRAYS

In [2]:
import numpy as np

In [2]:
py_list = [1,2,3]

## creating numpy array from python list

In [62]:
np.array(py_list)

array([1, 2, 3])

In [4]:
nested_list = [[1,2], [3,4], [5,6]]

In [5]:
nested_list

[[1, 2], [3, 4], [5, 6]]

## creating numpy nested array from nested list

In [63]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

## creating numpy array from 0 to 11 with values for every two multiplication

In [32]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## creating numpy array of 3 zeros 

In [14]:
np.zeros(3)

array([0., 0., 0.])

## creating numpy array of zeros on type int (default float)

In [33]:
np.zeros((4,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## creating numpy array of 3 ones

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

## creating numpy array of zeros and ones

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## creating numpy array of 2 random numbers using rand generator

In [24]:
np.random.rand(2)

array([0.90546508, 0.46531131])

In [25]:
np.random.rand(3,4)

array([[0.15904775, 0.11020146, 0.53766966, 0.11784218],
       [0.24680846, 0.69987493, 0.07088265, 0.04374249],
       [0.49903378, 0.65687711, 0.5845582 , 0.88636514]])

## creating numpy array of random numbers using randn generator

In [26]:
np.random.randn(5,5)

array([[-1.09641316, -0.78310808, -0.24762636,  2.81144651,  1.32801165],
       [-0.79896286, -1.66926378,  0.66393853, -0.34476932, -0.59655041],
       [ 1.10938482,  1.27212277, -1.82180895,  1.32383835,  1.70245529],
       [-1.01017982,  0.96422475,  1.78710008,  0.31247006, -0.66162341],
       [-1.34791768,  1.71956914,  0.04990186, -1.426704  , -0.05765342]])

## creating numpy array of random numbers using randint generator

In [29]:
np.random.randint(1, 100, (2,3))

array([[40, 14, 83],
       [25, 43, 94]])

## setting seed to generate pseudo-random number

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
arr = np.arange(25)

In [36]:
rand_arr = np.random.randint(0,50,10)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
rand_arr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## checking shape of array

In [42]:
arr.shape

(25,)

## reshaping array to be 5 by 5, NOTICE: reshape does not affect original array it creates new instance of array

In [46]:
arr = arr.reshape(5,5)

In [47]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## display maximum value in numpy array

In [52]:
rand_arr.max()

39

## display index (placement) of max value in numpy array

In [51]:
rand_arr.argmax()

7

## display minimum value in numpy array

In [55]:
rand_arr.min()

2

## display index (placement) of min value in numpy array

In [56]:
rand_arr.argmin()

9

## display type of values in numpy array

In [58]:
rand_arr.dtype

dtype('int64')

In [59]:
rand_d_arr = np.random.rand(4)

In [60]:
rand_d_arr.dtype

dtype('float64')

# NUMPY INDEX SELECTION

In [73]:
arr = np.arange(0,11)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr[8]

8

In [67]:
arr[1:5]

array([1, 2, 3, 4])

In [68]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr[-1:]

array([10])

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr[0:5] = 100

In [76]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### Changing values of sliced array affects original array

In [77]:
arr = np.arange(0,11)

In [78]:
slice_of_arr = arr[0:5]

In [79]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
slice_of_arr[:] = 99

In [82]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [83]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### work on new instance of same array and not affects original

In [84]:
arr_copy = arr.copy()

In [85]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [86]:
arr_copy[:] = 101

In [87]:
arr_copy

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [88]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [90]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [91]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### first value of shape is number of rows, second value if shape is number of columns

In [92]:
arr_2d.shape

(3, 3)

In [93]:
arr_2d[0]

array([ 5, 10, 15])

In [94]:
arr_2d[0,2]

15

In [97]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [98]:
arr = np.arange(0, 11)

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [101]:
bool_arr = arr > 4

In [102]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

### filtering only values with True, it means values that are greater than 4

In [103]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [104]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

### NUMPY OPERATIONS

In [106]:
arr = np.arange(0, 10)

In [107]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [109]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [110]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [111]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [112]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [113]:
arr - 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### When devided by zero Numpy display warning instead of error and change 0/0 to NaN value.

In [115]:
arr / arr

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [116]:
1 / 0

ZeroDivisionError: division by zero

In [117]:
1/ arr

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [118]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [119]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [120]:
np.log(arr)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [121]:
arr.sum()

45

In [122]:
arr.mean()

4.5

In [123]:
arr.var()

8.25

In [124]:
arr.max()

9

In [125]:
arr.std()

2.8722813232690143

In [126]:
arr.min()

0

In [129]:
array_2d = np.arange(0, 25).reshape(5,5)

In [133]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [130]:
array_2d.sum()

300

### Sum with axis = 0 make sum across columns

In [131]:
array_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

### Sum with axis = 1 make sum across rows

In [132]:
array_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

# NUMPY EXERCISES

#### 2. Create an array of 10 zeros 

In [3]:
# CODE HERE
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
# DON'T WRITE HERE

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# DON'T WRITE HERE

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [6]:
np.linspace(5, 5, 10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
# DON'T WRITE HERE

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create an array of the integers from 10 to 50

In [10]:
np.linspace(10, 50, 41, dtype='int')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
# DON'T WRITE HERE

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50

In [12]:
np.linspace(10, 50, 21, dtype='int')

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
# DON'T WRITE HERE

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# DON'T WRITE HERE

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Create a 3x3 identity matrix

In [16]:
np.eye(3).reshape(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# DON'T WRITE HERE

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Use NumPy to generate a random number between 0 and 1<br><br>&emsp;NOTE: Your result's value should be different from the one shown below.

In [17]:
np.random.rand(1)

array([0.80708697])

In [9]:
# DON'T WRITE HERE

array([0.65248055])

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution<br><br>&emsp;&ensp;NOTE: Your result's values should be different from the ones shown below.

In [18]:
np.random.rand(25)

array([0.05846617, 0.08592498, 0.53639554, 0.61909132, 0.53349557,
       0.09120634, 0.555408  , 0.51105112, 0.12123662, 0.90194433,
       0.19104872, 0.18185229, 0.78037122, 0.47526859, 0.22142084,
       0.18111777, 0.86798239, 0.02861739, 0.29258862, 0.74184114,
       0.03637491, 0.3075017 , 0.97110885, 0.39061337, 0.89381107])

In [10]:
# DON'T WRITE HERE

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Create the following matrix:

In [31]:
np.linspace(0.01, 1, 100, dtype='float').reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
# DON'T WRITE HERE

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

In [32]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# DON'T WRITE HERE

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs:

In [33]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code that reproduces the output shown below.<br><br>&emsp;&ensp;Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.

In [48]:
# CODE HERE
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# DON'T WRITE HERE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code that reproduces the output shown below.

In [55]:
number_arr = mat == 20
mat[number_arr][0]

20

In [15]:
# DON'T WRITE HERE

20

#### 15. Write code that reproduces the output shown below.

In [60]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [16]:
# DON'T WRITE HERE

array([[ 2],
       [ 7],
       [12]])

#### 16. Write code that reproduces the output shown below.

In [62]:
mat[-1:]

array([[21, 22, 23, 24, 25]])

In [17]:
# DON'T WRITE HERE

array([21, 22, 23, 24, 25])

#### 17. Write code that reproduces the output shown below.

In [64]:
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# DON'T WRITE HERE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy Operations

#### 18. Get the sum of all the values in mat

In [65]:
mat.sum()

325

In [19]:
# DON'T WRITE HERE

325

#### 19. Get the standard deviation of the values in mat

In [68]:
mat.std()

7.211102550927978

In [20]:
# DON'T WRITE HERE

7.211102550927978

#### 20. Get the sum of all the columns in mat

In [70]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [21]:
# DON'T WRITE HERE

array([55, 60, 65, 70, 75])