# NUMPY ARRAYS

In [ ]:
import numpy as np

In [2]:
py_list = [1,2,3]

## creating numpy array from python list

In [62]:
np.array(py_list)

array([1, 2, 3])

In [4]:
nested_list = [[1,2], [3,4], [5,6]]

In [5]:
nested_list

[[1, 2], [3, 4], [5, 6]]

## creating numpy nested array from nested list

In [63]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

## creating numpy array from 0 to 11 with values for every two multiplication

In [32]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## creating numpy array of 3 zeros 

In [14]:
np.zeros(3)

array([0., 0., 0.])

## creating numpy array of zeros on type int (default float)

In [33]:
np.zeros((4,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## creating numpy array of 3 ones

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

## creating numpy array of zeros and ones

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## creating numpy array of 2 random numbers using rand generator

In [24]:
np.random.rand(2)

array([0.90546508, 0.46531131])

In [25]:
np.random.rand(3,4)

array([[0.15904775, 0.11020146, 0.53766966, 0.11784218],
       [0.24680846, 0.69987493, 0.07088265, 0.04374249],
       [0.49903378, 0.65687711, 0.5845582 , 0.88636514]])

## creating numpy array of random numbers using randn generator

In [26]:
np.random.randn(5,5)

array([[-1.09641316, -0.78310808, -0.24762636,  2.81144651,  1.32801165],
       [-0.79896286, -1.66926378,  0.66393853, -0.34476932, -0.59655041],
       [ 1.10938482,  1.27212277, -1.82180895,  1.32383835,  1.70245529],
       [-1.01017982,  0.96422475,  1.78710008,  0.31247006, -0.66162341],
       [-1.34791768,  1.71956914,  0.04990186, -1.426704  , -0.05765342]])

## creating numpy array of random numbers using randint generator

In [29]:
np.random.randint(1, 100, (2,3))

array([[40, 14, 83],
       [25, 43, 94]])

## setting seed to generate pseudo-random number

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
arr = np.arange(25)

In [36]:
rand_arr = np.random.randint(0,50,10)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
rand_arr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## checking shape of array

In [42]:
arr.shape

(25,)

## reshaping array to be 5 by 5, NOTICE: reshape does not affect original array it creates new instance of array

In [46]:
arr = arr.reshape(5,5)

In [47]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## display maximum value in numpy array

In [52]:
rand_arr.max()

39

## display index (placement) of max value in numpy array

In [51]:
rand_arr.argmax()

7

## display minimum value in numpy array

In [55]:
rand_arr.min()

2

## display index (placement) of min value in numpy array

In [56]:
rand_arr.argmin()

9

## display type of values in numpy array

In [58]:
rand_arr.dtype

dtype('int64')

In [59]:
rand_d_arr = np.random.rand(4)

In [60]:
rand_d_arr.dtype

dtype('float64')